In [1]:
#Preprocessing of the dataset

In [6]:
# Step 1 : Import Required Libraries

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [7]:
# Step 2 : Load Dataset

df = pd.read_csv("agriculture_pbl_dataset.csv")

# Displaying first 5 rows
df.head()

,Region,Rainfall,Temperature,Soil_Moisture,Soil_pH,Nitrogen,Phosphorus,Potassium,Irrigation,Crop_Area,...,Sunlight,Humidity,Altitude,Wind_Speed,Groundwater,Crop_Diversity,Mechanization,Yield_Variance,Avg_Yield,Date
0,Himachal Pradesh,1201.569424,NaN,53.679563,6.5,56.543419,33.554044,32.136748,46.247007,1894.613096,...,7,65.609045,1200.425100,6,10.257541,0.75,0.707765,0.154710,3.201550,2023-04-01
1,Tamil Nadu,757.638766,29,41.679606,7.0,71.681802,29.473451,33.893236,89.231907,985485.071894,...,9,64.419266,215.614601,9,11.260415,0.7,0.693836,0.156560,3.775694,2023-04-01
2,Haryana,613.993849,25,NaN,7.5,75.850080,41.581121,39.766414,95.471554,3979.560035,...,8.2,64.570050,244.434639,11,13.438724,0.7,0.767334,0.174542,4.735220,2023/02/01
3,punjab,627.489137,NaN,44.299021,seven.two,78.541471,35.503769,44.258846,87.424738,4355.548987,...,8 hours,64.009329,249.815847,10,13.993817,75%,0.849821,0.139407,4.427345,01/01/23
4,Punjab,618.382204,24,46.510076,7.2,77.333975,39.149462,41.956297,93.679763,4284.875280,...,8h,60.010019,257.795174,10,14.355341,0.75,0.890524,0.151426,4.290304,2023-01-01

In [8]:
# Step 3 : Checking Basic Information

# Check column names, datatype, missing values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region          1050 non-null   str
 1   Rainfall        1000 non-null   float64
 2   Temperature     950 non-null    str
 3   Soil_Moisture   1000 non-null   float64
 4   Soil_pH         1050 non-null   str
 5   Nitrogen        1000 non-null   float64
 6   Phosphorus      1000 non-null   float64
 7   Potassium       1050 non-null   float64
 8   Irrigation      1000 non-null   float64
 9   Crop_Area       1050 non-null   float64
 10  Fertilizer      1050 non-null   str
 11  Pesticide       1000 non-null   str
 12  Sunlight        1000 non-null   str
 13  Humidity        1000 non-null   float64
 14  Altitude        1050 non-null   float64
 15  Wind_Speed      1050 non-null   str
 16  Groundwater     1000 non-null   float64
 17  Crop_Diversity  1050 non-null   str
 18  Mechanization   1000 non-null   float64
 19  Yield_Variance  1000 non-null   float64
 20  Avg_Yield       1000 non-null   float64
 21  Date            1050 non-null   str
dtypes: float64(13), str(9)
memory usage: 180.6 KB

In [9]:
# Step 4 : Remove Unnecessary Columns

# Region and Date are not useful for K-Means clustering
# because they are labels, not numerical learning features

df.drop(columns=["Region", "Date"], inplace=True)

In [10]:
# Verifying columns after dropping
print(df.columns)

Index(['Rainfall', 'Temperature', 'Soil_Moisture', 'Soil_pH', 'Nitrogen',
       'Phosphorus', 'Potassium', 'Irrigation', 'Crop_Area', 'Fertilizer',
       'Pesticide', 'Sunlight', 'Humidity', 'Altitude', 'Wind_Speed',
       'Groundwater', 'Crop_Diversity', 'Mechanization', 'Yield_Variance',
       'Avg_Yield'],
      dtype='str')

In [12]:
# Step 5 : Convert Text Columns to Numeric

# Some columns contain values like:
# "8 hours", "75%", "120 kg", "7.2 pH"

cols_to_clean = [
    "Temperature",
    "Soil_pH",
    "Fertilizer",
    "Pesticide",
    "Sunlight",
    "Wind_Speed",
    "Crop_Diversity"
]

for col in cols_to_clean:
    
    # Extract only numeric values using regex
    df[col] = df[col].astype(str).str.extract(r'(\d+\.?\d*)')[0]
    
    # Convert extracted values into numeric datatype
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Checking if conversion worked
df.head()

,Rainfall,Temperature,Soil_Moisture,Soil_pH,Nitrogen,Phosphorus,Potassium,Irrigation,Crop_Area,Fertilizer,Pesticide,Sunlight,Humidity,Altitude,Wind_Speed,Groundwater,Crop_Diversity,Mechanization,Yield_Variance,Avg_Yield
0,1201.569424,NaN,53.679563,6.5,56.543419,33.554044,32.136748,46.247007,1894.613096,140.0,7.0,7.0,65.609045,1200.425100,6.0,10.257541,0.75,0.707765,0.154710,3.201550
1,757.638766,29.0,41.679606,7.0,71.681802,29.473451,33.893236,89.231907,985485.071894,200.0,12.0,9.0,64.419266,215.614601,9.0,11.260415,0.70,0.693836,0.156560,3.775694
2,613.993849,25.0,NaN,7.5,75.850080,41.581121,39.766414,95.471554,3979.560035,210.0,NaN,8.2,64.570050,244.434639,11.0,13.438724,0.70,0.767334,0.174542,4.735220
3,627.489137,NaN,44.299021,NaN,78.541471,35.503769,44.258846,87.424738,4355.548987,9999.0,12.0,8.0,64.009329,249.815847,10.0,13.993817,75.00,0.849821,0.139407,4.427345
4,618.382204,24.0,46.510076,7.2,77.333975,39.149462,41.956297,93.679763,4284.875280,9999.0,12.0,8.0,60.010019,257.795174,10.0,14.355341,0.75,0.890524,0.151426,4.290304

In [13]:
# Step 6 : Check Missing Values

# Display number of missing values in each column
print(df.isnull().sum())

Rainfall           50
Temperature       100
Soil_Moisture      50
Soil_pH            50
Nitrogen           50
Phosphorus         50
Potassium           0
Irrigation         50
Crop_Area           0
Fertilizer        100
Pesticide         100
Sunlight           50
Humidity           50
Altitude            0
Wind_Speed         50
Groundwater        50
Crop_Diversity      0
Mechanization      50
Yield_Variance     50
Avg_Yield          50
dtype: int64

In [14]:
# Step 7 : Handle Missing Values

# Fill missing values using mean of each column
# Mean imputation is suitable for clustering projects
df.fillna(df.mean(numeric_only=True), inplace=True)

# Verify all missing values are removed
print(df.isnull().sum())

Rainfall          0
Temperature       0
Soil_Moisture     0
Soil_pH           0
Nitrogen          0
Phosphorus        0
Potassium         0
Irrigation        0
Crop_Area         0
Fertilizer        0
Pesticide         0
Sunlight          0
Humidity          0
Altitude          0
Wind_Speed        0
Groundwater       0
Crop_Diversity    0
Mechanization     0
Yield_Variance    0
Avg_Yield         0
dtype: int64

In [15]:
# Step 8 : Check Duplicate Rows

# Count duplicate rows
print(df.duplicated().sum())

0

In [16]:
# Step 9 : Remove Duplicate Rows

# Remove duplicates if any exist
# (Safe to run even if duplicates = 0)
df.drop_duplicates(inplace=True)

In [22]:
# Step 10 : Handle Outliers using IQR Method

# Instead of deleting rows,
# we cap extreme values using clip()

for col in df.columns:
    
    # Calculate Q1 (25%) and Q3 (75%)
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    # Calculate IQR
    IQR = Q3 - Q1
    
    # Define lower and upper bounds
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    # Cap values outside bounds
    df[col] = df[col].clip(lower, upper)

#Displaying first 5 rows are outlier handling
print("Dataset after Outlier Handling:")
print(df.head())

Dataset after Outlier Handling:
      Rainfall  Temperature  Soil_Moisture  Soil_pH   Nitrogen  Phosphorus  \
0  1201.569424    31.421053      53.679563    6.500  56.543419   33.554044
1   757.638766    29.000000      41.679606    7.000  71.681802   29.473451
2   613.993849    25.000000      48.744043    7.500  75.850080   41.581121
3   627.489137    31.421053      44.299021    7.115  78.541471   35.503769
4   618.382204    24.000000      46.510076    7.200  77.333975   39.149462

   Potassium  Irrigation    Crop_Area  Fertilizer  Pesticide  Sunlight  \
0  32.136748   46.247007  2047.374633       140.0   7.000000       7.0
1  33.893236   89.231907  5972.324185       200.0  12.000000       9.0
2  39.766414   95.471554  3979.560035       210.0   9.789474       8.2
3  44.258846   87.424738  4355.548987       277.5  12.000000       8.0
4  41.956297   93.679763  4284.875280       277.5  12.000000       8.0

    Humidity    Altitude  Wind_Speed  Groundwater  Crop_Diversity  \
0  65.609045  546.774177         6.0    10.257541            0.75
1  64.419266  215.614601         9.0    11.260415            0.70
2  64.570050  244.434639        11.0    13.438724            0.70
3  64.009329  249.815847        10.0    13.993817            0.90
4  60.010019  257.795174        10.0    14.355341            0.75

   Mechanization  Yield_Variance  Avg_Yield
0       0.707765        0.154710   3.201550
1       0.693836        0.156560   3.775694
2       0.767334        0.174542   4.735220
3       0.849821        0.139407   4.427345
4       0.888705        0.151426   4.290304

In [23]:
# Step 11 : Apply StandardScaler

# K-Means uses distance calculations
# so all features must be on same scale

scaler = StandardScaler()

# Fit and transform the dataset
scaled_data = scaler.fit_transform(df)

# Convert scaled array back to DataFrame
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)

# Display first 5 rows after Standard Scaling
print("Dataset after Standard Scaling:")
print(scaled_df.head())

Dataset after Standard Scaling:
   Rainfall  Temperature  Soil_Moisture   Soil_pH  Nitrogen  Phosphorus  \
0  0.577079     1.528892       0.501549 -0.542526 -1.347283   -0.244281
1 -0.474170     0.630255      -0.717453  0.331844  0.137897   -1.057842
2 -0.814329    -0.854449       0.000180  1.206215  0.546834    1.356104
3 -0.782371     1.528892      -0.451363  0.532949  0.810878    0.144442
4 -0.803937    -1.225625      -0.226755  0.681592  0.692414    0.871296

   Potassium  Irrigation  Crop_Area  Fertilizer  Pesticide  Sunlight  \
0  -1.147703   -1.508541  -2.141981   -1.231144  -1.823204 -1.144160
1  -0.867271    1.423335   2.152128    0.117762   1.444803  1.547982
2   0.070407    1.848923  -0.028065    0.342579   0.000000  0.471125
3   0.787644    1.300073   0.383288    1.860098   1.444803  0.201911
4   0.420032    1.726710   0.305967    1.860098   1.444803  0.201911

   Humidity  Altitude  Wind_Speed  Groundwater  Crop_Diversity  Mechanization  \
0  0.160338  1.897391   -1.170975    -1.469264        0.693137       0.363784
1  0.036000 -0.183823    0.029536    -1.206667        0.096585       0.207976
2  0.051758 -0.002700    0.829878    -0.636290        0.096585       1.030158
3 -0.006841  0.031119    0.429707    -0.490942        2.482794       1.952906
4 -0.424791  0.081266    0.429707    -0.396279        0.693137       2.387884

   Yield_Variance  Avg_Yield
0       -1.190426  -0.935156
1       -1.146096   0.216835
2       -0.715187   2.142073
3       -1.557138   1.524339
4       -1.269117   1.249372

In [24]:
# Step 12 : Verify Scaling

# Mean should be close to 0
# Standard deviation should be close to 1

print(scaled_df.describe())

           Rainfall   Temperature  Soil_Moisture       Soil_pH      Nitrogen  \
count  1.050000e+03  1.050000e+03   1.050000e+03  1.050000e+03  1.050000e+03
mean   1.928616e-16 -1.241758e-15   5.007635e-16 -7.308440e-16  8.729525e-16
std    1.000477e+00  1.000477e+00   1.000477e+00  1.000477e+00  1.000477e+00
min   -2.392323e+00 -1.967978e+00  -2.286373e+00 -2.116392e+00 -2.430498e+00
25%   -6.410776e-01 -4.832732e-01  -7.540376e-01 -5.425259e-01 -6.768037e-01
50%   -1.703360e-01 -1.120970e-01   1.797738e-04 -1.790377e-02  1.029407e-04
75%    5.264195e-01  6.302552e-01   6.559305e-01  5.067184e-01  6.920031e-01
max    2.277665e+00  2.300548e+00   2.770883e+00  2.080585e+00  2.745213e+00

         Phosphorus     Potassium    Irrigation     Crop_Area    Fertilizer  \
count  1.050000e+03  1.050000e+03  1.050000e+03  1.050000e+03  1.050000e+03
mean  -6.970086e-16  1.251909e-16  5.142976e-16 -4.314009e-16  7.274604e-17
std    1.000477e+00  1.000477e+00  1.000477e+00  1.000477e+00  1.000477e+00
min   -2.623414e+00 -2.424775e+00 -2.231769e+00 -2.141981e+00 -1.231144e+00
25%   -6.780471e-01 -7.366256e-01 -7.125183e-01 -5.316899e-01 -6.691001e-01
50%    9.121212e-04 -2.081601e-01 -5.188114e-02  6.732096e-02 -3.318736e-01
75%    6.188641e-01  6.334765e-01  6.048370e-01  5.418373e-01  3.425792e-01
max    2.564231e+00  2.688630e+00  2.580870e+00  2.152128e+00  1.860098e+00

          Pesticide      Sunlight      Humidity      Altitude    Wind_Speed  \
count  1.050000e+03  1.050000e+03  1.050000e+03  1.050000e+03  1.050000e+03
mean   3.721891e-16  3.383537e-16  1.705303e-15  2.436147e-16  2.233134e-16
std    1.000477e+00  1.000477e+00  1.000477e+00  1.000477e+00  1.000477e+00
min   -1.823204e+00 -2.490231e+00 -2.268427e+00 -2.177290e+00 -1.571146e+00
25%   -5.160011e-01 -4.711248e-01 -5.673779e-01 -6.492850e-01 -7.708049e-01
50%    0.000000e+00  0.000000e+00 -2.021950e-03 -7.203961e-02  2.953640e-02
75%    7.912018e-01  8.749461e-01  5.666546e-01  3.693853e-01  4.297070e-01
max    2.098405e+00  1.547982e+00  2.267703e+00  1.897391e+00  2.230475e+00

        Groundwater  Crop_Diversity  Mechanization  Yield_Variance  \
count  1.050000e+03    1.050000e+03   1.050000e+03    1.050000e+03
mean   7.443781e-17   -1.150403e-16  -2.300805e-16    3.383537e-17
std    1.000477e+00    1.000477e+00   1.000477e+00    1.000477e+00
min   -2.033114e+00   -2.289625e+00  -2.105849e+00   -1.703512e+00
25%   -7.002383e-01   -4.999677e-01  -7.346093e-01   -7.414444e-01
50%   -9.103082e-02    9.658467e-02  -1.145695e-01   -7.345790e-02
75%    5.752477e-01    6.931371e-01   5.143880e-01    6.181375e-01
max    2.488477e+00    2.482794e+00   2.387884e+00    2.657510e+00

          Avg_Yield
count  1.050000e+03
mean   1.353415e-17
std    1.000477e+00
min   -2.639834e+00
25%   -6.643154e-01
50%    4.202034e-04
75%    6.526967e-01
max    2.628215e+00

In [26]:
#Saving the cleaned dataset
scaled_df.to_csv("clean_scaled_agriculture_dataset.csv", index=False)

In [ ]:
print("\n=====End of Data Pre =====")